name: .NET Core
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Create dummy .NET project
      run: 'New-Item -ItemType Directory -Path dotnet-demo -Force New-Item -ItemType  Directory
        -Path dotnet-demo\DemoProject -Force

        $csproj = @"
<Project  Sdk=""Microsoft.NET.Sdk""> <PropertyGroup> <OutputType>Exe</OutputType>     <TargetFramework>net6.0</TargetFramework>
        </PropertyGroup> </Project>
"@ $csproj | Out-File -FilePath dotnet-demo\DemoProject\DemoProject.csproj  -Encoding
        utf8

        $program = ''using System; class Program { static void  Main() => Console.WriteLine("Hello,
        World!"); }'' $program | Out-File  -FilePath dotnet-demo\DemoProject\Program.cs
        -Encoding utf8 '
    - name: Install dotnet-sonarscanner
      run: 'dotnet tool install -g dotnet-sonarscanner

        '
    - name: Begin SonarScanner
      env:
        SONAR_TOKEN: $SONAR_TOKEN
        SONAR_HOST_URL: $SONAR_HOST_URL
        sonarProjectKey: DummyProjectKey
        sonarProjectName: DummyProjectName
      run: 'dotnet sonarscanner begin /k:"DummyProjectKey" /n:"DummyProjectName" /d:sonar.host.url=$SONAR_HOST_URL
        /d:sonar.login=$SONAR_TOKEN /d:sonar.exclusions="*/bin/,/obj/"

        '
    - name: Restore
      run: 'dotnet restore dotnet-demo/DemoProject/DemoProject.csproj

        '
    - name: Build
      run: 'dotnet build dotnet-demo/DemoProject/DemoProject.csproj --configuration
        Release

        '
    - name: End SonarScanner
      env:
        SONAR_TOKEN: $SONAR_TOKEN
      run: 'dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

        '
    - name: Test
      run: dotnet test dotnet-demo/DemoProject/DemoProject.csproj --configuration
        Release --collect:"XPlat Code Coverage"
