name: .NET Core
on:
  push:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
    - name: Dummy Restore Step
      run: "Write-Host \"\u2705 Simulating dotnet restore (no .sln needed)\"
"
    - name: Install dotnet-sonarscanner
      run: 'dotnet tool install -g dotnet-sonarscanner

        '
    - name: Begin SonarScanner
      env:
        SONAR_TOKEN: $SONAR_TOKEN
        SONAR_HOST_URL: $SONAR_HOST_URL
      run: 'dotnet sonarscanner begin /k:"github.com/$GITHUB_REPOSITORY" /d:sonar.host.url=$SONAR_HOST_URL
        /d:sonar.token=$SONAR_TOKEN

        '
    - name: Build
      run: 'dotnet build

        '
    - name: End SonarScanner
      env:
        SONAR_TOKEN: $SONAR_TOKEN
        SONAR_HOST_URL: $SONAR_HOST_URL
      run: 'dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

        '
    - name: Test with XPlat Code Coverage
      run: dotnet test --configuration Release --collect "XPlat Code Coverage"
