name: .NET6 Demo Workflow
on:
  push:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET6 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Create Dummy .NET6 Project
      run: 'mkdir dotnet-demo

        mkdir dotnet-demo/DemoProject

        echo ^<Project Sdk="Microsoft.NET.Sdk"^> > dotnet-demo/DemoProject/DemoProject.csproj

        echo ^ ^<PropertyGroup^> >> dotnet-demo/DemoProject/DemoProject.csproj

        echo ^ ^<OutputType^>Exe^</OutputType^> >> dotnet-demo/DemoProject/DemoProject.csproj

        echo ^ ^<TargetFramework^>net6.0^</TargetFramework^> >> dotnet-demo/DemoProject/DemoProject.csproj

        echo ^ ^</PropertyGroup^> >> dotnet-demo/DemoProject/DemoProject.csproj

        echo ^</Project^> >> dotnet-demo/DemoProject/DemoProject.csproj

        echo using System; class Program { static void Main() => Console.WriteLine("Hello,
        World!"); } > dotnet-demo/DemoProject/Program.cs

        '
    - name: Install dotnet-sonarscanner
      run: dotnet tool install -g dotnet-sonarscanner
    - name: Begin SonarQube Analysis
      env:
        SONAR_TOKEN: $SONAR_TOKEN
        SONAR_HOST_URL: $SONAR_HOST_URL
      run: 'dotnet sonarscanner begin ^

        /k:"DummyProjectKey" ^

        /n:"DummyProjectName" ^

        /d:sonar.host.url="$SONAR_HOST_URL" ^

        /d:sonar.login="$SONAR_TOKEN" ^

        /d:sonar.exclusions="**/bin/**,**/obj/**"

        '
    - name: Restore Dependencies
      run: dotnet restore dotnet-demo/DemoProject/DemoProject.csproj
    - name: Build Project
      run: dotnet build dotnet-demo/DemoProject/DemoProject.csproj --configuration
        Release
    - name: End SonarQube Analysis
      env:
        SONAR_TOKEN: $SONAR_TOKEN
      run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
    - name: Run Tests with Code Coverage
      run: dotnet test dotnet-demo/DemoProject/DemoProject.csproj --configuration
        Release --collect:"XPlat Code Coverage"
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
