name: .NET Core
on:
  push:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
    - name: Install dotnet-sonarscanner
      run: dotnet tool install -g dotnet-sonarscanner
    - name: Restore dependencies
      run: dotnet restore
    - name: Begin SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: 'dotnet sonarscanner begin /k:"GitHub" /d:sonar.token=${SONAR_TOKEN} /d:sonar.host.url=${SONAR_HOST_URL}

        '
    - name: Build
      run: dotnet build
    - name: End SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: dotnet sonarscanner end /d:sonar.token=${SONAR_TOKEN} /d:sonar.host.url=${SONAR_HOST_URL}
    - name: Test with XPlat Code Coverage
      run: dotnet test --configuration Release --collect:"XPlat Code Coverage"
